-
  name: Install Git and Docker
  hosts: ansible-node
  tasks:
    - name: Git check
      yum:
        name: git
        state: present

    - name: Install Docker
      yum:
        name: docker
        state: present
