-
  name: Install Git and Docker
  hosts: ip-172-31-39-241.ap-south-1.compute.internal
  tasks:
    - name: Git check
      yum:
        name: git
        state: present

    - name: Install Docker
      yum:
        name: docker
        state: present
